### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by una** [rmurphey/ttlpodcast.com#4]
Maybe we should just put the "About" page in the footer as a bigger footer?

**Comment by rmurphey** [comment]
It occurred to me too that there isn't really a whole lot here, and I'm not sure there's going to be. I'd be just fine with making an extended footer, though it might then make sense to make the footer a bit more suited to reading whole sentences. Right now it is appropriately subdued, but it seems that might make less sense if there is more content.

**Comment by una** [comment]
Put it in the footer in the last commit
